name:                rat
version:             0.1.0.0
github:              "githubuser/rat"
license:             BSD3
author:              "Jaroslaw Jantura"
maintainer:          "jjantura@gmail.com"
copyright:           "2022 Jaroslaw Jantura"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            IOT

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/rat#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- net-mqtt
- cryptonite
- text
- bytestring
- async
- mtl
- transformers
- network-uri

library:
  source-dirs: src

executables:
  rat-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rat

tests:
  rat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rat
